### ISSUE TITLE
cdap_streaming_program_run error 404

### ISSUE THREAD

**Issue by pradeepchc** [GoogleCloudPlatform/terraform-provider-cdap#100]
We are facing an error while running the streaming pipeline in datafusion instance.
Terraform is not able to recognise the app name.

Code :

data "google_client_config" "current" {}

terraform {
  required_providers {
    cdap = {
      source = "GoogleCloudPlatform/cdap"
      version = "0.9.0"
    }
  }
}

provider "cdap" {
  #.
  host  = "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.googleusercontent.com/api/"
  token = data.google_client_config.current.access_token
}

resource "cdap_streaming_program_run" "test" {
  app       = "testpoc"  ( the app name is referred from deployed pipeline name)
  type      = "spark"

  runtime_arguments = {
    "system.profile.name" = "SYSTEM:dataproc"
  }
}

-------error------------

Error: 404: 
│ <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>  <ins>That’s all we know.</ins>
│ 
│ 
│   with cdap_streaming_program_run.test,
│   on main.tf line 18, in resource "cdap_streaming_program_run" "test":
│   18: resource "cdap_streaming_program_run" "test" {

--------------------------------------------------------------

**Comment by umairidris** [comment]
You may wish to create the run in UI and then list the runs through the REST API to see what the right values to set should be

https://cloud.google.com/data-fusion/docs/reference/cdap-reference

Endpoints: https://github.com/GoogleCloudPlatform/terraform-provider-cdap/blob/master/cdap/resource_streaming_program_run.go#L306

**Comment by pradeepchc** [comment]
dear @umairidris thanks for your reply.
We are trying to deploying the pipeline using terraform script.
when we are trying to execute the script we are facing the below error, We tried also with the REST API and ended with same result.
Initially we created the cdap application using the export json file and later we are referring it (application name) in streaming run module.

**Comment by umairidris** [comment]
Hi @pradeepchc,

This TF provider is making REST calls under the hood, so please continue working through the REST API calls until it works. See 

https://cloud.google.com/data-fusion/docs/reference/cdap-reference#batch_pipeline_run_records

If there is a bug in the provider we are happy to accept contributions.

If you are unable to get the REST API working, I would encourage you to raise this issue with cloud support who can get you in touch with the Data Fusion team themselves as they don't monitor this repo.

**Comment by pradeepchc** [comment]
@umairidris : Yes we are now only working on the REST API
These rest api also gives the same error as below, are we missing something while deploying pipeline?

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>

**Comment by umairidris** [comment]
The data fusion team will be better able to support you, consider filing a ticket with cloud support: https://cloud.google.com/support-hub
