### ISSUE TITLE
Release prebuilt binaries

### ISSUE THREAD

**Issue by lastomato** [GoogleCloudPlatform/terraform-provider-cdap#34]
It will be great if we could release pre-built binaries, building a binary locally requires setting up the Go toolchain which is not trivial for some users.

**Comment by umairidris** [comment]
Hi @lastomato 

This is already the case. Have you seen the releases page: https://github.com/GoogleCloudPlatform/terraform-provider-cdap/releases?

The website includes using the release binary as well: https://googlecloudplatform.github.io/terraform-provider-cdap/#installation

**Comment by lastomato** [comment]
Thanks! There used to be a releases tab under the repo name, GitHub seems to remove it now. Anyways thanks for the response!
