### ISSUE TITLE
Simplify installing with terraform init

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/terraform-provider-cdap#35]
Let's explore exposing this provider through the [terraform registry](https://registry.terraform.io/) so it can be more seemlessly installed for users with terraform init.

**Comment by umairidris** [comment]
As discussed this will likely not happen for now as this provider is not popular enough for Hashicorp to officially maintain it. It does show up under the community providers though: https://www.terraform.io/docs/providers/type/community-index.html
