### ISSUE TITLE
"host" misnomer in provider

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/terraform-provider-cdap#41]
the provider takes an input "host"
however, it expects scheme, host and path
e.g.
"https://example-instance-example-project-dot-usc1.datafusion.googleusercontent.com/api/"

In my mind this should be named "service_endpoint"  (consistent w/ [data fusion rest api](https://cloud.google.com/data-f%22https://example-instance-example-project-dot-usc1.datafusion.googleusercontent.com/api/%22usion/docs/reference/rest/v1beta1/projects.locations.instances#Instance)) or  "rest_endpoint" (more general for for OSS / non data fusion CDAP users)

Unfortunately this is an interface breaking change.
Fortunately I think we are the only users of this provider so far.

**Comment by umairidris** [comment]
So the reason I called it host was to be consistent with the more popular kubernetes provider: https://www.terraform.io/docs/providers/kubernetes/index.html#statically-defined-credentials.

Also, depending on how you host your CDAP instance you will have different hostnames. For example, the cdap docs bring up an instance on localhost with a port: https://docs.cask.co/cdap/4.0.1/en/developers-manual/getting-started/start-stop-cdap.html.

Another rather unfortunate thing is the CDF service_endpoint cannot used as-is, as the actual service endpoint needed for the cdap provider is ${service_endpoint}/api, else I was going to use that before.

Given above, I thought it was best to keep things consistent with other similarly functioning providers and give examples on how to set it.

If you don't have a strong preference let's keep it as host.
