### ISSUE TITLE
Error Message Misleading

### ISSUE THREAD

**Issue by svetakvsundhar** [GoogleCloudPlatform/terraform-provider-cdap#57]
When using jsonencode(file()) in the main.tf file of a module, an error saying "Unable to marshal type map(string)" is thrown. However, this issue here is that jsonencode() isn't needed as file() can parse through a JSON file. Is it possible to change the error message to point to the JSON, as the "unable to marshal type.." indicates that is an issue with the Go code?

**Comment by umairidris** [comment]
I don't think this is related to the provider, rather Terraform itself so I think you're better off requesting this in https://github.com/hashicorp/terraform.

And I am pretty sure you are right that it is Go code related asthe  jsonencode probably just gets converted to a json.Marshal call in Terraform.
