### ISSUE TITLE
gitignore ignores docs templates.

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/terraform-provider-cdap#60]
Right now the gitignore file has a `generate_docs`
I believe the intention is to ignore the `generate_docs` executable.
However there is a side effect of ignoring the directory `tools/generate_docs`
We should add:
```
!tools/**
```

**Comment by umairidris** [comment]
So I tested this before pushing and it seemed to be like gitignore did not apply recursively, but maybe I was wrong...

**Comment by umairidris** [comment]
Fixed by #58
