### ISSUE TITLE
Users seeing 504s

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/terraform-provider-cdap#71]
I personally got sporadic 502s / 504s today from CDF today.
Worked on running terraform apply again. 
I think we should treat CDF as a flaky server and  retry on all 5xx codes and add a few retries to protect users of this provider from this flakiness.
Mike Turk mentioned 502s and 504s on his instance yesterday.

**Comment by umairidris** [comment]
This was fixed upstream.
