### ISSUE TITLE
v0.4.0 provider name

### ISSUE THREAD

**Issue by turkm507** [GoogleCloudPlatform/terraform-provider-cdap#77]
Hey there.  did the name of the 0.4.0 binary get accidentally changed?  The words cdap and provider are switched.
terraform-cdap-provider_v0.4.0_linux-amd64
terraform-provider-cdap_v0.3.0_linux-amd64
Noticed it because i got an error when i first tried to use it... but renaming it fixes it.
Just wanted to mention it.

**Comment by umairidris** [comment]
Ops! Thanks for reporting this, I built these from a new bash script I wrote: https://github.com/GoogleCloudPlatform/terraform-provider-cdap/pull/76 and I put the wrong name there :( 

Fixed in the script and updated release. Let me know if you run into any problems!
