### ISSUE TITLE
Improve docs 

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/terraform-provider-cdap#8]
User should be able to read docs and understand what resources are implemented, what fields are exposed (or NOT exposed) and special behavior (when an application resource is added does it start the pipeline?)

We might be able to autogenerate some of this? https://github.com/segmentio/terraform-docs

**Comment by umairidris** [comment]
Unfortunately that tool is only for modules, not providers :( I think we have to manually do it... at least I think the gcp provider does it manually (though their "magic modules" overlay automates most of it).

**Comment by umairidris** [comment]
We can write a small tool that can take a resource from the map in https://godoc.org/github.com/hashicorp/terraform/helper/schema#Resource and write out to a file.
