### ISSUE TITLE
Error dialing Google

### ISSUE THREAD

**Issue by jasonmcboyd** [GoogleCloudPlatform/terraform-provider-cdap#81]
# Problem

Executing `terraform plan` or `terraform apply` results in the following error:

> Error: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
> on main.tf line 18, in provider "cdap":
> 18: provider "cdap" {

In the example code below, removing the cdap resource prevents the script from failing and builds the data fusion instance so there is no issue with the google provider configuration.

# Version

Terraform v0.12.24
+ provider.cdap v0.5.0
+ provider.google-beta v3.22.0

# Minimum Code To Reproduce
```terraform
provider "google-beta" {
  credentials = "<credentials>"
  project     = "<project-id>"
  region      = "us-west1"
}

resource "google_data_fusion_instance" "instance" {
  provider = google-beta
  name     = "example"
  region   = "us-west1"
  type     = "BASIC"
}

data "google_client_config" "current" {
  provider = google-beta
}

provider "cdap" {
  host  = "${google_data_fusion_instance.instance.service_endpoint}/api/"
  token = data.google_client_config.current.access_token
}

resource "cdap_namespace" "dev3" {
  provider = cdap
  name     = "dev"
}
```

**Comment by umairidris** [comment]
Did you try removing the cdap provider and resource but keeping the google_client_config data source? It seems that is the one that's failing to find credentials.

If you're running locally try running `gcloud auth application-default login`.

**Comment by jasonmcboyd** [comment]
Hi thanks for your help. Yes, as I mentioned in the problem statement, if I remove the cdap resource it executes successfully and creates the data fusion instance. I'm trying to run it locally and from a docker container. Neither one is working.

**Comment by umairidris** [comment]
This is unusual because in the code we don't search for the default credentials and instead just rely on the token being passed in.

What happens if you use this resource instead:

```
resource "local_file" "foo" {
    content     = data.google_client_config.current.access_token
    filename = "/tmp/token"
}
```

Does /tmp/token get populated correctly?

**Comment by jasonmcboyd** [comment]
It does.

**Comment by umairidris** [comment]
Thanks, I did a bit of digging and believe I found the cause. Sent #82

**Comment by umairidris** [comment]
I released v0.6.0. Please give it a try

**Comment by jasonmcboyd** [comment]
Wow! I step into a meeting and come back to find the problem is solved! Thanks so much. Yes, v0.6.0 is working for me now.

**Comment by umairidris** [comment]
Glad to hear it! Hope you find the provider useful.
