### ISSUE TITLE
provider publishing on registry.terraform.io

### ISSUE THREAD

**Issue by des-esseintes** [GoogleCloudPlatform/terraform-provider-cdap#85]
Hey guys,
We are trying to use the provider with terraform 0.13 and the workaround to make it work is quite ugly. Could you please post it to the registry?
Thanks!

**Comment by umairidris** [comment]
@des-esseintes it's available now at https://registry.terraform.io/providers/GoogleCloudPlatform/cdap/latest. Thanks!

**Comment by des-esseintes** [comment]
Much appreciated!
