### ISSUE TITLE
Get "/v3/namespaces": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by Guimove** [GoogleCloudPlatform/terraform-provider-cdap#92]
Hello,

I've deployed a data fusion instance (with a private network, namespace and so) but now every time I launch a plan or an apply I get the following error : 

Error: Get "/v3/namespaces": unsupported protocol scheme ""

![2021-04-22 12_02_52-Hyper](https://user-images.githubusercontent.com/1172067/115696373-e9d36580-a362-11eb-8b1a-8ff2952366d8.png)

I can provide logs and/or everything that can help.

Thanks,

**Comment by umairidris** [comment]
Are you able to communicate with the data fusion instance outside the provider? You can try the curl calls in https://cloud.google.com/data-fusion/docs/reference/cdap-reference. The provider is essentially making those same calls under the hood.

Off the top of my head I can think of lack of credentials (double check `gcloud auth login` and `gcloud auth application-default login`) or the fact the provider is not running in a place that the CDF instance is visible (try running in a gce vm inside the private network).

**Comment by Guimove** [comment]
you where right, it was becaus I was with a private instance :)
